### ISSUE TITLE
pinout unclear in version 1.2

### ISSUE THREAD

**Issue by SensorsIot** [hallard/RAK831-Zero#1]
Hi Charles
I used your board (the one you gave me in Amsterdam which was pre-soldered) to build a Gateway, but it does not work (the concentrator cnaoot be connected, the rest works ok). When I checked the PCB I found some strange things. On the 1.3a version of he Eagle files Pin 1 and 2 are 5V. On my board 23 and 24 are connected to 5 volts. Somehow everything seems mirrored. What is my mistake? The Neopixels are on the side of the RPI and the concentrator below your board.
Andreas

**Comment by hallard** [comment]
Andreas,
Yes before V1.3 the RAK831 concentrator board need to be plugged on top (concentrator above). that's not cool and my mistake. So that's why some silk numbering are wrong.
So to resume on V1.2 just plug the RAK on TOP and it works, don't bother with silk numbering

**Comment by hallard** [comment]
Solved in latest releases
