### ISSUE TITLE
Ethernet jack with PoE

### ISSUE THREAD

**Issue by jpmeijers** [hallard/RAK831-Zero#2]
Is there any chance you can add ethernet to the backplane, splitting out the passice PoE lines to the DC/DC, and the data lines to a usb ethernet module?

**Comment by edude03** [comment]
Standard PoE would be nice as well

**Comment by jpmeijers** [comment]
Yes. 802.3af would be nice, but more expensive to implement.

**Comment by hallard** [comment]
@Guys,
I designed this board to directly fit into the enclosure I'm using. Adding this hardware would oversize and not fit into the enclosure.
Anyway you can still use the board on a Raspberry (or clone) with Ethernet and just add POE splitter?
