### ISSUE TITLE
missing items from BOM

### ISSUE THREAD

**Issue by EtoTen** [hallard/RAK831-Zero#3]
Hi, I just assembled a v1.5a board but noticed I was missing some items that were not on the BOM (which I ordered from).

Can you please help me figure out what:

LED3, LED4, R1, R3 and Q1 should be?

The CR1220 holder was also missing but that is easier to guess.

Also the "R30-3000602" standoff is too short as it is only 6MM and I think these should be 2x instead of 1x on the BOM. 
Thanks!!

**Comment by hallard** [comment]
Hi,
Thanks for pointing that out, the BOM file as been updated.
https://octopart.com/bom-tool/bSeZiAE7

For the standoff, just let me know if you have a correct reference so I can update BOM also
